huggingface:
  model: "meta-llama/Llama-2-7b-hf"
  revision: "01c7f73d771dfac7d292323805ebc428287df4f9"
  tensors: true
pipeline:
  name: "nemo-megatron-llama-2-7b-peft"
  version: "v01"
  container: "nemo-megatron"
  steps:
    - name: hf_to_nemo
      description: "convert huggingface model to nemo model"
      config: hf_to_nemo.yaml
    - name: preprocess
      description: "preprocess data"
      config: preprocess.yaml
    - name: peft
      description: "peft of model"
      config: peft.yaml