huggingface:
  model: "mistralai/Mistral-7B-v0.1"
  revision: "26bca36bde8333b5d7f72e9ed20ccda6a618af24"
  tensors: true
pipeline:
  name: "nemo-megatron-mistral-7b-peft-dolphin"
  version: "v01"
  container: "nemo-megatron"
  steps:
    - name: hf_to_nemo
      description: "convert huggingface model to nemo model"
      config: hf_to_nemo.yaml
    - name: preprocess
      description: "preprocess data"
      config: preprocess.yaml
    - name: peft
      description: "peft of model"
      config: peft.yaml
    - name: peft_eval
      description: "peft evaluation of model"
      config: peft_eval.yaml
    - name: merge_peft_model
      description: "Merge peft model"
      config: merge_peft.yaml
    - name: nemo_to_hf
      description: "convert nemo model to huggingface model"
      config: nemo_to_hf.yaml